### ISSUE TITLE
Support empty arrays and null values

### ISSUE THREAD

**Issue by Malkiz** [phretaddin/schemapack#5]
These tests fail for the explained reasons:
```javascript
var tests = require('./tests');
tests.testValues({x: "varint"}, {x: null}) // converts value to 0 after decoding
tests.testValues({arr: ["varint"]}, {arr: []}) // converts value to [0] after decoding
tests.testValues({str: "string"}, {str: null}) // throws exception on encoding
tests.testValues({arr: ["string"]}, {arr: []}) // throws exception on encoding
tests.testValues({arr: ["string"]}, {arr: null}) // throws exception on encoding
tests.testValues({obj: { y: "varint"}}, {obj: null}) // throws exception on encoding
```
And there are probably other examples with other data types, but you get the idea.

**Comment by Adezandee** [comment]
Indeed, I detected an diff inside the current test actually. The homebrewed implementation of `deepEqual` seems flaky atm.

**Comment by phretaddin** [comment]
@Malkiz Thanks for looking in to this! I'll look in to this.

@Adezandee Yeah, I should probably use a different `deepEqual` function. The reason for the error is because of floating point precision so I need a custom method that takes a delta in to account. Otherwise, it will say the test didn't pass because the decoded value is 0.00000000001% different than the passed in value.

**Comment by Adezandee** [comment]
@phretaddin there should be a way around that to `parseFloat` with some precision constraint so that random number doesn't appear out of nowhere

**Comment by phretaddin** [comment]
* Switched to using `ava` `deepEqual` instead of my homebrew implementation
* Added support for empty arrays
* Added support for null strings

Still not sure how I want to handle null values for other data types. Closing for now since most issues are resolved. Maybe create an updated issue if you still have any problems?

**Comment by darrachequesne** [comment]
Hi! For future reference, as of `1.4.2`:

```js
var tests = require('./tests');
tests.testValues({x: "varint"}, {x: null}) // throws 'null does not match the type of number'
tests.testValues({arr: ["varint"]}, {arr: []}) // OK
tests.testValues({str: "string"}, {str: null}) // throws 'null does not match the type of string'
tests.testValues({arr: ["string"]}, {arr: []}) // OK
tests.testValues({arr: ["string"]}, {arr: null}) // throws 'Cannot read property 'length' of null'
tests.testValues({obj: { y: "varint"}}, {obj: null}) // throws 'Cannot read property 'y' of null'
```
