### ISSUE TITLE
fixed length elements

### ISSUE THREAD

**Issue by ajoslin103** [phretaddin/schemapack#9]
please consider supporting fixed-length elements

I have to read some messages that reserve 256bytes for a null terminated string

**Comment by phretaddin** [comment]
Could you explain further? I'm not exactly sure what you need.

**Comment by ajoslin103** [comment]
I want to use this library to read already written binary files, porting in c/c++ structs 

So far it's working very well -- but then I hit a case where these files have 256 byte fixed length, null-terminated strings... And your strings are variable length.

I think this could be done by adding a char type, and then adding the concept of a fixed length array (varuint length prefix) -- which I could convert to a string after reading...

Except, now I'm starting to think about these varuint length prefix's and the sorted schema properties -- and I'm wondering how much this is going to break your package and it's original intent...

Maybe we could use this project as the seed for another for reading and writing binary files?

**Comment by phretaddin** [comment]
Ah, I see. I actually toyed with the idea of making strings null terminated, but ended up deciding against it since I envisioned the library to mostly be used with WebSockets and it could be an attack vector via buffer overflow. Also, there wouldn't really be any space savings since the length prefix is usually one byte via varuint.

I suppose you could just add another datatype, "nstring" or something (null terminated string). Shouldn't be too hard. Just instead of writing a length prefix you end the `writeString` with a 0 byte. I don't think there's support for reading null terminated strings with the `node` Buffer though, so you'd have to write a small function to iterate the bytes until it encountered a 0, and then call `toString` on that block of bytes.

Here's some code that does that: https://github.com/JoshGlazebrook/smart-buffer/blob/master/lib/smart-buffer.js#L152

**Comment by ajoslin103** [comment]
But the problems' essence isn't reading and writing null-terminated strings 

It's reading binary data that other programs created.

I _really_ like how easily it goes when I'm copying struct defs over from the c/c++ code -- but then when I read data I'm running into the problem that your code didn't write that data, so there there issues (like ordered properties and fixed length structures without prefixed size indicators.

I can do a lot of the work, building off your project -- but I'm going to fall down on the bit-twiddling code.

Do I have your permission to use your code as a starting point for a binary-file processing library?  And would you collaborate?

**Comment by phretaddin** [comment]
Sure, you have my permission. I'll try to help as well. I'm not the greatest at bit twiddling but I'll try my best.
